version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456@Dev2
    ports:
      - '5437:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql

